### ISSUE TITLE
青蛙跳的时间复杂度？

### ISSUE THREAD

**Issue by by2101** [hrwhisper/algorithm_course#1]
我的思路使用逐步往前迭代，生成图的邻接矩阵的方法来做。
但是这样的话，在查看每一步前面所跳的步数 k 需要 O(n) 的时间。
我没有完全看懂你的代码，你的是把前面的节点存成邻接表了吗？这样的话，是不是最坏情况也需要 O(n) 呀？似乎不能常数次找到？

**Comment by hrwhisper** [comment]
hash 表

**Comment by by2101** [comment]
比如某一节点，前面有多个前驱节点，全部考察一遍的话，肯定要遍历一次啊。

**Comment by hrwhisper** [comment]
对啊，对于每个结点，可能遍历前面的结点，所以不是O(n^2)么？

**Comment by by2101** [comment]
对每一个节点，要考察遍历前面所有节点找到可能的 k，然后对于这个 k 不是还要考察后面所有的节点看符不符合条件吗？这样不是 O(n3)？

**Comment by hrwhisper** [comment]
不是，就是n^2，从前往后，当前结点x能跳到y, 把 x加入y可达的列表中，而这个列表长度最多为n。

**Comment by by2101** [comment]
我知道了
我看到你的代码有
if k > 0 and stone + k in dp:
这一步。我理解是判断是否存在距离为 stone + k 的石头。
判断 in dp 的话，用遍历的话，应该需要 O(n) 的。不知道 Python 对 dict 的实现，如果是用平衡树之类，也需要 O(logN) 吧？

**Comment by by2101** [comment]
查了一下文档。dict 的 in 是 O(1)。
牛！

**Comment by hrwhisper** [comment]
就是hash表的啦 如果c++的话可以unordered_map
