### ISSUE TITLE
转载、使用别人文章请注明出处！

### ISSUE THREAD

**Issue by nosense-4s1n** [hrwhisper/algorithm_course#2]
http://bitjoy.net/2016/01/29/algorithm-design-and-analysis-by-dbu/
放链接。自己明白。

**Comment by hrwhisper** [comment]
不好意思，你说的是我抄袭那个？
没有转载和使用
前面的题自己leetcode都刷过
https://www.hrwhisper.me/leetcode-algorithm-solution/
你的连接比百度文库的还少
搜  卜东波老师算法分析与设计作业答案2015版

**Comment by nosense-4s1n** [comment]
自己看6、7章节。

**Comment by nosense-4s1n** [comment]
自己看5、6章节。

**Comment by hrwhisper** [comment]
请问您是那个bitjoy.net 的站长么？
您能仔细的看一下区别然后再来说嘛？

**Comment by nosense-4s1n** [comment]
不承认？把句意稍作修改就不算抄袭了？相似度这么大都是巧合？
我很反感你一上来的态度。我有同学下学期会当你的助教的。

**Comment by hrwhisper** [comment]
我承认您的题解也写的不错。
但是为什么相同的解法就是抄袭？
但是假如做法一样的话，要如何表述完全不一样？
PS：网络流那些是经典的题很多acm书上都会讲解
您可以看看您的题解和卜东波老师算法分析与设计作业答案2015版的，也很多一样。 :)
我只能添加在其它参考资料上 :)
